name: WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_EDITORS: false
          SHOW_LANGUAGE: true
          SHOW_TIMEZONE: true
          SHOW_LINES_OF_CODE: false
          SHOW_COMMIT: false
          SHOW_LOC_CHART: false
          SHOW_PROFILE_VIEWS: true
