name: WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.WAKA_PAT }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          SHOW_LINES_OF_CODE: "True"
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "True"
